# Site settings
title: squirkio.com
description: >- # this means to ignore newlines until "baseurl:"
  A home page for squirkio
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://squirkio.com" # the base hostname & protocol for your site
google_analytics: G-SNXYRXFP0T
twitter_username: slimbods
github_username: squirkio
bluesky_username: squirkio.com
linkedIn_username: simonquirk
threads_username: slimbos
# Build settings
theme: jekyll-theme-slate
markdown: kramdown
permalink: /:year/:title/
