# Site settings
title: squirkio.com
description: >- # this means to ignore newlines until "baseurl:"
  A home page for squirkio
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://squirkio.com" # the base hostname & protocol for your site
twitter_username: slimbods
github_username: squirkio
bluesky_username: squirkio
linkedIn_username: simonquirk
threads_username: slimbos

# Build settings
theme: jekyll-theme-hacker
markdown: kramdown
permalink: /:year/:title/
